export const ALL_USER_ROLES = ["user", "admin"] as const;

export const ALL_JOB_TITLES = [
  "General Contractor",
  "Plumber",
  "Electrician",
  "Carpenter",
  "Gardener",
  "Painter",
  "Roofer",
  "Landscaper",
  "HVAC Technician",
  "Flooring Specialist",
  "Mason",
  "Welder",
  "Window Installer",
  "Appliance Repair Technician",
  "Handyman",
  "Pool Technician",
  "Locksmith",
  "Glazier",
  "Drywall Installer",
  "Tiler",
  "Pest Control Specialist",
  "Siding Installer",
  "Fencing Contractor",
  "Cabinetmaker",
  "Arborist",
  "Deck Builder",
  "Demolition Specialist",
  "Solar Panel Installer",
  "Excavation Contractor",
  "Steel Fabricator",
  "Insulation Installer",
  "Soundproofing Specialist",
] as const;
